// <auto-generated />
using System;
using CourseLibrary.API.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CourseLibrary.API.Migrations
{
    [DbContext(typeof(CourseLibraryContext))]
    [Migration("20210522154758_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CourseLibrary.API.Entities.ComplaintDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Area")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("ContactNumber")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("IssueDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("ComplaintDetails");

                    b.HasData(
                        new
                        {
                            Id = new Guid("db578f7a-1334-4abe-a0db-beddafd33190"),
                            Area = "Swargate",
                            City = "Pune",
                            ContactNumber = "",
                            CreatedDate = new DateTime(2021, 5, 22, 15, 47, 58, 578, DateTimeKind.Utc).AddTicks(8183),
                            EmailAddress = "ab123@gmail.com",
                            IssueDescription = "Since Last Four Days we are since Network Range Issues in Area. Please can you resolve asap",
                            LastModifiedDate = new DateTime(2021, 5, 22, 21, 17, 58, 578, DateTimeKind.Local).AddTicks(9022),
                            Title = "Internet Range Issue"
                        },
                        new
                        {
                            Id = new Guid("3793561d-a485-499f-a034-dddfc2917fca"),
                            Area = "Magarpatta",
                            City = "Pune",
                            ContactNumber = "",
                            CreatedDate = new DateTime(2021, 5, 22, 15, 47, 58, 581, DateTimeKind.Utc).AddTicks(5385),
                            EmailAddress = "ab123@gmail.com",
                            IssueDescription = "Increase in Call Drop Since Last Few Days",
                            LastModifiedDate = new DateTime(2021, 5, 22, 21, 17, 58, 581, DateTimeKind.Local).AddTicks(5404),
                            Title = "Call Drop Issue"
                        },
                        new
                        {
                            Id = new Guid("e7375cd1-b138-429e-95ae-be489c4a1ef4"),
                            Area = "Magarpatta",
                            City = "Pune",
                            ContactNumber = "",
                            CreatedDate = new DateTime(2021, 5, 22, 15, 47, 58, 581, DateTimeKind.Utc).AddTicks(5462),
                            EmailAddress = "231abc@gmail.com",
                            IssueDescription = "Increase in Call Drop Since Last Few Days",
                            LastModifiedDate = new DateTime(2021, 5, 22, 21, 17, 58, 581, DateTimeKind.Local).AddTicks(5463),
                            Title = "Call Drop Issue"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
