// <auto-generated />
using System;
using CourseLibrary.API.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CourseLibrary.API.Migrations
{
    [DbContext(typeof(CourseLibraryContext))]
    [Migration("20210522051818_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CourseLibrary.API.Entities.ComplaintDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Area")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("ContactNumber")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("IssueDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("ComplaintDetails");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e788a3bc-0841-4bba-a819-2df8e2a5775d"),
                            Area = "Swargate",
                            City = "Pune",
                            ContactNumber = "",
                            CreatedDate = new DateTime(2021, 5, 22, 5, 18, 17, 989, DateTimeKind.Utc).AddTicks(9681),
                            EmailAddress = "ab123@gmail.com",
                            IssueDescription = "Since Last Four Days we are since Network Range Issues in Area. Please can you resolve asap",
                            LastModifiedDate = new DateTime(2021, 5, 22, 10, 48, 17, 990, DateTimeKind.Local).AddTicks(797),
                            Title = "Internet Range Issue"
                        },
                        new
                        {
                            Id = new Guid("4556c7c8-5cf8-4c9b-98a9-a7fb6083bd11"),
                            Area = "Magarpatta",
                            City = "Pune",
                            ContactNumber = "",
                            CreatedDate = new DateTime(2021, 5, 22, 5, 18, 17, 992, DateTimeKind.Utc).AddTicks(8062),
                            EmailAddress = "ab123@gmail.com",
                            IssueDescription = "Increase in Call Drop Since Last Few Days",
                            LastModifiedDate = new DateTime(2021, 5, 22, 10, 48, 17, 992, DateTimeKind.Local).AddTicks(8094),
                            Title = "Call Drop Issue"
                        },
                        new
                        {
                            Id = new Guid("9fb1f08d-1c03-49da-be11-e90c443e5ffc"),
                            Area = "Magarpatta",
                            City = "Pune",
                            ContactNumber = "",
                            CreatedDate = new DateTime(2021, 5, 22, 5, 18, 17, 992, DateTimeKind.Utc).AddTicks(8202),
                            EmailAddress = "231abc@gmail.com",
                            IssueDescription = "Increase in Call Drop Since Last Few Days",
                            LastModifiedDate = new DateTime(2021, 5, 22, 10, 48, 17, 992, DateTimeKind.Local).AddTicks(8204),
                            Title = "Call Drop Issue"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
